Variable Value Provision using a delegate
BrianAA/dashchat pull request #2
Opened 2022-08-12 17:25 UTC by LionRichter

Simplified variable provision by using a simple delegate `string (string variableName)`.

Kept event based provision as a fallback.

2022-08-12 17:58 UTC, LionRichter commented
@BrianAA Keeping a fallback to allow for graceful updates. I'd love to remove them, the amount of required changes should be minimal. Please give feedback.

One thing I need to mention: The option to assign multiple VariableProviders could have been useful. This was possible with the event based system. Wishes?

2022-08-14 14:32 UTC, BrianAA requested changes
Love the updates! This is great let's make the changes by dropping the old way of doing it all together and just keep this version.

2022-08-14 14:32 UTC, BrianAA commented on DashChat.cs
> +    public static DashChat instance { get; private set; }
I like this short and concise for singleton pattern

2022-08-14 14:32 UTC, BrianAA commented on DashChat.cs
> +    }
Very cool understand what you mean about this being more performant now.

2022-08-14 14:32 UTC, BrianAA commented on DashChat.cs
> +
Lets just drop this all together now since no one other than us are playing with the script no sense of supporting a deprecation warning.

2022-09-11 19:06 UTC, merged